multitask_ranking_metric:
  class_path: comet_multi_cand.models.MultitaskRankingMetric
  init_args:
    # this can be either proportion or number of steps
    nr_frozen_epochs: 3_000
    keep_embeddings_frozen: True
    optimizer: AdamW
    encoder_learning_rate: 1.0e-06
    learning_rate: 1.5e-05
    layerwise_decay: 0.95
    encoder_model: XLM-RoBERTa
    pretrained_model: xlm-roberta-large
    pool: avg
    layer: mix
    layer_transformation: sparsemax
    layer_norm: False
    loss: mse
    dropout: 0.1
    batch_size: 16
    train_data:
      - data/csv/train_multitask.csv
    validation_data:
      - data/csv/dev_multitask.csv
    hidden_sizes:
      - 2048
      - 1024
    activations: Tanh

trainer: trainer_pairwise.yaml
early_stopping: early_stopping_multitask.yaml
model_checkpoint: model_checkpoint_multitask.yaml